# Generated by Django 2.2.1 on 2019-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articclecolume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticcleColume',
        ),
    ]
