# Generated by Django 2.2.1 on 2019-06-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_delete_articclecolume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
    ]
